languages:
  # --- Common properties ---------------------------------------------------
  #  type            (required): Specifies the output language (java | javascript | typescript | python).
  #
  #  file_naming     (optional): Specifies the file naming convention (snake | screaming_snake | camel | pascal | kebap). Defaults to the file-name without the extension.
  #  property_naming (optional): Specifies the property naming convention (snake | screaming_snake | camel | pascal | kebap).
  #  type_naming     (optional): Specifies the naming convention for the generated type (snake | screaming_snake | camel | pascal | kebap). The default value is language specific.
  #  indent          (optional): Specifies the amount of spaces before each constant. Defaults to 4.
  # -------------------------------------------------------------------------

  # --- Java specific properties --------------------------------------------
  #  package (required): Specifies the Java package name.
  # -------------------------------------------------------------------------
  - type: java
    file_naming: pascal
    type_naming: pascal
    package: my.test.package

  # --- JavaScript/TypeScript specific properties ---------------------------
  #  export (optional): Specifies how to export the class (esm | common_js | none). Defaults to esm.
  # -------------------------------------------------------------------------
  - type: javascript
    file_naming: screaming_snake
    export: common_js

  - type: typescript
    indent: 4

  - type: python
    file_naming: snake
    property_naming: screaming_snake

properties:
  # --- Common properties ---------------------------------------------------
  #  type    (required): Specifies the constant data type (bool | int | float | double | string | regex).
  #  name    (required): Specifies the constant's name.
  #  value   (required): Specifies the constant's value.
  #
  #  comment (optional): Adds an extra comment to the constant.
  #  hidden  (optional): Constants serves as helper and will not be written to the final result.
  # -------------------------------------------------------------------------

  - type: bool
    name: myBoolean
    value: true

  - type: int
    name: myInteger
    value: 142

  - type: float
    name: myFloat
    value: 322f  # Float with float specifier. However, an additional specifier (f) is not required and will be trimmed.

  - type: double
    name: myDouble
    value: 233.9

  - type: string
    name: myString
    value: Hello World
    hidden: true  # If a property should act as a helper but should not be written to the generated file, it must be marked as 'hidden'.

  - type: regex
    name: myRegex
    value: Test Reg(E|e)x
    comment: Just another RegEx.  # Variables can be described using the comment property.

  - type: string
    name: mySubstitutedString
    value: Sometimes I just want to scream ${myString}!
