languages:
  - type: java                        # Specifies the output language. Supported values are: java | javascript | typescript | python
    file_naming: pascal               # (Optional) Specifies the file naming convention. Supported values: snake | screaming_snake | camel | pascal | kebap
    property_naming: screaming_snake  # (Optional) Specifies the property naming convention. Supported values: snake | screaming_snake | camel | pascal | kebap
    type_naming: pascal               # (Optional) Specifies the naming convention for the generated type. The default value is language specific.
                                      #            Supported values: snake | screaming_snake | camel | pascal | kebap
    indent: 4                         # (Optional) Specifies the amount of spaces before each constant. Defaults to 4.
    package: my.test.package          # (Java specific) For Java, a package name must be specified.

  - type: javascript
    file_naming: screaming_snake
    export: common_js  # (Optional + JavaScript/TypeScript specific) Defines how to export the class. Supported values are: esm | common_js | none. Defaults to esm.

  - type: typescript
    file_naming: kebap

  - type: python
    file_naming: snake
    property_naming: screaming_snake

properties:
  - type: bool       # Specifies the constant data type. Supported values: bool | int | float | double | string | regex
    name: myBoolean  # Specifies the constant's name.
    value: true      # Specifies the constant's value.

  - type: int
    name: myInteger
    value: 142

  - type: float
    name: myFloat
    value: 322f  # Float with float specifier. However, an additional specifier (f) is not required and will be trimmed.

  - type: double
    name: myDouble
    value: 233.9

  - type: string
    name: myString
    value: Hello World
    hidden: true  # If a property should act as a helper but should not be written to the generated file, it must be marked as 'hidden'.

  - type: regex
    name: myRegex
    value: Test Reg(E|e)x
    comment: Just another RegEx.  # Variables can be described using the comment property.

  - type: string
    name: mySubstitutedString
    value: Sometimes I just want to scream ${myString}!
