# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: confluent pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  release:
    types:
      - 'created'

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Github environment
      uses: actions/checkout@v2
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Prepare Python
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install ruff
    - name: Run tests
      run: |
        echo "I'm in $(pwd)"
        ls -la
        python -m unittest discover tests || exit -1
    - name: Lint
      run: |
        python -m ruff check . || exit -1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test_and_lint
    if: ${{ github.event_name == 'release' }}
    steps:
    - name: Prepare Github environment
      uses: actions/checkout@v2
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip pip install build
    - name: Build package
      run: |
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
    
